language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec rake
env:
  - DB=postgresql
before_script:
  - cp config/database.yml{.travis,}
  - cp config/secrets.yml{.travis,}
  - psql -c 'create database new_blog_test' -U postgres
cache: bundler
