# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ec789544d611e47f0988438b3b8911f20458fcac528c9ed136066683135b815fc0b02564f186471c1467bdeffbc1c425a0c60bb45c4aaee439a9d7a704da3a

test:
  secret_key_base: 30cc9c7cefd541d6ecf000661895316639cdee68e5aa7e9d98d91f62b1fb97b0e2945b7935d0483033941ebef112a58fe105ce4770e55bebd04a82a22753a25b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
